version: "3"

services:

  database:
    image: postgres
    container_name: database
    env_file:
      - database.env
    networks:
      - my-network

  grabber:
    build:
      context: ./grabber
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: grabber
    command: python main.py
    networks:
      - my-network
    depends_on:
      - database

  trader:
    build:
      context: ./trader
    container_name: trader
    env_file:
      - trader.env
    networks:
      - my-network
    depends_on:
      - database

  worker:
    build:
      context: ./worker
    container_name: worker
    env_file:
      - worker.env
    networks:
      - my-network
    depends_on:
      - database
      - trader

networks:
  my-network: